// /!\ this file is generated by the `script/extract.js` program, do not edit by hand

// decorate the fixers object through the side effects of the various imports
import "./properties.js"
import "./values.js"
import "./selectors_and_at-rules.js"
import "./extras.js"