// /!\ this file is generated by the `script/extract.js` program, do not edit by hand

import {root, fixers as self} from '../fixers.js'

if (typeof getComputedStyle === 'function') new function() {
	// Properties that accept properties as their value
	self.valueProperties = [
		'transition',
		'transition-property',
		'will-change'
	]
	// Add class for current prefix
	root.className += ' ' + self.prefix;
}